### ISSUE TITLE
Route Enhancer

### ISSUE THREAD

**Issue by typo3max** [derhansen/plain_faq#85]
Do it give a route enhancer? Thank you!

**Comment by derhansen** [comment]
No examples in the docs, since this is really straight forward. 

```
  FaqDetailPlugin:
    type: Extbase
    limitToPages:
      - 123
    extension: PlainFaq
    plugin: Pidetail
    routes:
      -
        routePath: '/{faq_title}'
        _controller: 'Faq::detail'
        _arguments:
          faq_title: faq
    defaultController: 'Faq::detail'
    aspects:
      faq_title:
        type: PersistedAliasMapper
        tableName: tx_plainfaq_domain_model_faq
        routeFieldName: slug
  FaqListDetailPlugin:
    type: Extbase
    limitToPages:
      - 456
    extension: PlainFaq
    plugin: Pilistdetail
    routes:
      -
        routePath: /
        _controller: 'Faq::list'
      -
        routePath: '/detail/{faq_title}'
        _controller: 'Faq::detail'
        _arguments:
          faq_title: faq
    defaultController: 'Faq::list'
    aspects:
      faq_title:
        type: PersistedAliasMapper
        tableName: tx_plainfaq_domain_model_faq
        routeFieldName: slug
```
